# Generated by Django 4.2.2 on 2023-09-25 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("housepriceprediction", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MyModel",
        ),
    ]
